name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Team3Assig
    - name: Build
      run: dotnet build --no-restore
      working-directory: Team3Assig
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: TestProject

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: Team3Assig
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          usedocker: true
          docker_build_args: |
            VERSION
        env:
          VERSION: 1.0.0.${{ github.run_number }}
